### ISSUE TITLE
您好，请问该项目有参考文档吗？

### ISSUE THREAD

**Issue by kevin-lh** [Clownsw/openvasScan#1]
在学习openvas的使用，但不知道这个项目如何运行，请问您可否方便提供些参考资料？感激不尽

**Comment by Clownsw** [comment]
> 在学习openvas的使用，但不知道这个项目如何运行，请问您可否方便提供些参考资料？感激不尽

openvas-scanner安装:[ https://github.com/greenbone/openvas-scanner/blob/main/INSTALL.md]( https://github.com/greenbone/openvas-scanner/blob/main/INSTALL.md)
openvas使用文档: [https://docs.greenbone.net/API/GMP/gmp-22.04.html](https://docs.greenbone.net/API/GMP/gmp-22.04.html)
官方论坛: [https://forum.greenbone.net/](https://forum.greenbone.net/)

**Comment by Clownsw** [comment]
> 在学习openvas的使用，但不知道这个项目如何运行，请问您可否方便提供些参考资料？感激不尽

项目参考使用文档编写

**Comment by kevin-lh** [comment]
好的谢谢您，麻烦再问一下，请问该项目必须在安装有openvas的机器上运行吗？请问在哪里配置宿主机的IP呢？是在web/src/config/requestInterceptor.js中吗

**Comment by Clownsw** [comment]
> 好的谢谢您，麻烦再问一下，请问该项目必须在安装有openvas的机器上运行吗？请问在哪里配置宿主机的IP呢？是在web/src/config/requestInterceptor.js中吗

是的项目必须跑在已安装openvas-scanner的机器上。如果要配置server ip 更改web/src/config/requestInterceptor.js即可

**Comment by kevin-lh** [comment]
谢谢您，我再尝试一下！

**Comment by kevin-lh** [comment]
请问我已经部署了openvas但运行项目会显示跨域请求报错。这里的ip是服务器ip，那端口号应该是什么呀？axios.defaults.baseURL = 'http://192.166.0.92:1111/'

**Comment by Clownsw** [comment]
> 器

请给出截图

**Comment by kevin-lh** [comment]
![image](https://user-images.githubusercontent.com/61111136/226881327-9ad8c0db-df11-4245-aa24-39cece8f42e7.png)
![image](https://user-images.githubusercontent.com/61111136/226881651-84c82b8e-f1f6-4b52-9e9e-31c81dd1d5d0.png)
请问p1中ip是主机ip（部署有openvas的），那端口应该是什么呢

**Comment by Clownsw** [comment]
> ![image](https://user-images.githubusercontent.com/61111136/226881327-9ad8c0db-df11-4245-aa24-39cece8f42e7.png) ![image](https://user-images.githubusercontent.com/61111136/226881651-84c82b8e-f1f6-4b52-9e9e-31c81dd1d5d0.png) 请问p1中ip是主机ip（部署有openvas的），那端口应该是什么呢

我这边没法复现你这种情况, 您可以检查一下环境
